    certroundcube:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
        - cb_conf:/etc/letsencrypt
        - cb_www_rc:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
